server.port=8088

spring.datasource.url=jdbc:mysql://localhost:3306/dbpurchase
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update

spring.sql.init.mode=never
spring.jpa.show-sql=true


VendorServiceConsumer.serviceURL=http://localhost:8087
VendorServiceConsumer.apiURL=/vendor/controller/getVendors

MaterialServiceConsumer.serviceURL=http://localhost:8082

MaterialCategoryConsumer.apiURL=/category/controller/getCategoryDetails
MaterialCategoryConsumer.apiURLForById=/category/controller/getCategoryDetails/

MaterialTypeConsumer.apiURL=/type/controller/getTypeDetails
MaterialTypeConsumer.apiURLByCategoryId=/type/controller/getTypeDetailsByCategoryId/

UnitServiceConsumer.apiURL=/unit/controller/getUnitDetails
UnitServiceConsumer.apiURLByCategoryId=/unit/controller/getUnitsByCategoryId/